
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

-- --------------------------------------------------------

DROP TABLE IF EXISTS `email_templates`;

--
-- Table structure for table `email_templates`
--
CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_name` varchar(350) NOT NULL,
  `template_subject` varchar(500) NOT NULL,
  `template_body` text NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `created_by` varchar(200) NOT NULL,
  `modified_by` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `email_templates`
-- 27-11-2013
--

INSERT INTO `email_templates` (`id`, `template_name`, `template_subject`, `template_body`, `created`, `modified`, `created_by`, `modified_by`) VALUES
(1, 'Reset Password', 'Reset Password', '\r\n                        <h2 style="font-size: 24px; margin: 30px 0px 25px 0px;  font-weight: normal;">Reset Password</h2>\r\n\r\n<table>\r\n    <tbody><tr>\r\n        <td>Hi |@username@|,<br><br></td>\r\n    </tr>\r\n    <tr>\r\n        <td>You recently asked to reset your password in Patients4Life.&nbsp;</td>\r\n    </tr>    \r\n    <tr>\r\n        <td><br>To reset your password, please click <a style="text-decoration: none; cursor: default;">here.</a></td>\r\n    </tr>\r\n    <tr><td><br>If you are not able to click the link above, please copy and paste the link below to your browser.<br></td></tr></tbody></table>\r\n<a style="text-decoration: none; cursor: default;">|@link@|</a>\r\n<p style="margin: 30px 0px 0px 0px;">Thanks,</p>\r\n<p style="margin: 1px 0px 0px 0px;">Patients4Life Team</p>                    ', '2013-10-24 16:11:16', '2013-11-08 13:06:18', 'admin', '1'),
(2, 'Account Activation Mail', 'Activate Account', '\r\n\r\n                        <h2 style="font-size: 24px; margin: 30px 0px 25px 0px;  font-weight: normal;">Activate Account</h2>\r\n\r\n<table>\r\n    <tbody><tr>\r\n        <td>Hi |@username@|,<br><br></td>\r\n    </tr>\r\n    <tr>\r\n        <td>Please click <a href="|@link@|" style="text-decoration: none; cursor: default;">here</a> to active your account.</td>\r\n    </tr>\r\n    <tr><td><br>If you are not able to click the link above, please copy and paste the link below to your browser.</td></tr></tbody></table>\r\n<a style="text-decoration: none; cursor: default;">|@link@|</a>\r\n<p style="margin: 30px 0px 0px 0px;">Thanks,</p>\r\n<p style="margin: 1px 0px 0px 0px;">Patients4Life Team</p>                    ', '2013-10-24 18:40:55', '2013-10-29 08:43:14', 'admin', '1'),
(3, 'Welcome Mail', 'Welcome to Patients4Life', '\r\n\r\n                        <h2 style="font-size: 24px; margin: 30px 0px 25px 0px;  font-weight: normal;">Welcome to Patients4Life</h2>Hi |@username@|,<br><br>Congrats! You are successfully registered with Patients4Life using the following credentials:<br>Username:  |@username@|<br>Email:  |@email@|<br><p style="margin: 30px 0px 0px 0px;">Thanks,</p>\r\n<p style="margin: 1px 0px 0px 0px;">Patients4Life Team</p>                    ', '2013-10-25 17:03:22', '2013-11-19 06:11:48', '1', '1'),
(4, 'Event Invites', 'Patients4Life: Invitation for Event', '\n                        \n\n                        <div><br></div>Hi |@username@|,<div><br></div><div>You have been invited to join the event |@event-name@|.<br></div><div>To know more details click <span style="cursor: default;"><a href="|@link@|">here</a></span>.<br></div><div><br></div><div>If you are not able to click the link above, please copy and paste the link below to your browser.<br></div><div>|@link@|<br></div><div><br></div><div><div>Thanks,</div><div>Patients4Life Team</div></div>                                        ', '2013-11-08 00:00:00', '2013-11-19 11:05:09', '1', '1'),
(5, 'mail to event creator', 'RSVP for event in Patients4Life', '\r\n\r\n                        \r\n\r\n                        \r\n\r\n                        \r\n\r\n                        \r\n\r\n                        <table class="table sortable no-margin" cellspacing="0" width="100%" style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal; background-color: rgb(255, 255, 255); margin-left: 0.33em; margin-bottom: -0.67em;"><tbody><tr><td class="padleft" width="100%" colspan="2"><div id="email_body_container"><br>Hi&nbsp;<span style="color: rgb(34, 34, 34); font-family: arial, sans-serif; line-height: normal; background-color: transparent;">|@name@|</span><span style="background-color: transparent;">,</span></div><div id="email_body_container"><br><div><span style="background-color: transparent;">|@username@|</span><font color="#222222" face="arial, sans-serif"><span style="line-height: normal;">&nbsp;updated RSVP for the event "|@event-name@|" as&nbsp;</span></font><span style="background-color: transparent; line-height: normal;"><font color="#222222" face="arial, sans-serif">|@status@|.</font></span><br></div><div><br></div><div>Thanks,</div><div>Patients4Life Team</div></div></td></tr></tbody></table>\r\n\r\n                        \r\n\r\n                                                                                                                                                                    ', '2013-11-07 04:56:50', '2013-11-21 13:42:44', '1', '1'),
(6, 'mail to all event members on delete event', 'Event has been cancelled', '<table class="table sortable no-margin" cellspacing="0" width="100%" style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal; background-color: rgb(255, 255, 255); margin-left: 0.33em; margin-bottom: -0.67em;"><tbody><tr><td class="padleft" width="100%" colspan="2"><div id="email_body_container">Hi&nbsp;|@username@|,<div><div style="line-height: normal;"><br><div>&nbsp; &nbsp; The event "|@event-name@|" has been cancelled by the creator of the event.</div><div><br></div><div>Thanks,</div><div>Patients4Life Team</div></div></div></div></td></tr></tbody></table>\r\n\r\n                                            ', '2013-11-15 09:24:18', '2013-11-19 06:12:36', '1', '1'),
(7, 'Update Event Notificatiion Mail', 'Event Updated', '\r\n                        \r\n                        \r\n                        \r\n\r\n                        <div><br>Hi |@username@|,</div><div><br></div><div>The event |@event-name@| has been updated recently.<br></div><div>To know more details click <span style="cursor: default;"><a href="|@link@|">here</a></span>.<br></div><div><br></div><div>If you are not able to click the link above, please copy and paste the link below to your browser.<br></div><div>|@link@|<br></div><div><br></div><div><div>Thanks,</div><div>Patients4Life Team</div></div>                                                                                ', '2013-11-20 06:21:40', '2013-11-20 07:34:24', '1', '1'),
(8, 'send daily report mail to event creators', 'Patients4Life : Event RSVP details on |@date@|', '\r\n\r\n                        \r\n\r\n                        <div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Hi |@event-creator-username@|,<br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><span style="color: rgb(34, 34, 34); font-family: arial, sans-serif;">RSVP details for the Events on&nbsp;</span>|@date@|<span style="color: rgb(34, 34, 34); font-family: arial, sans-serif;">&nbsp;is given below:</span></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">|@daily-mail-data@|</div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><div>Thanks,</div><div>Patients4Life team.</div></div>\r\n\r\n                                                                                    ', '2013-11-21 12:42:08', '2013-11-22 12:00:34', '1', '1'),
(9, 'Invite Community Member', 'Invitation to join community', '<div><br></div>Hi |@username@|,<div><br></div><div>You have been added to the community |@group-name@|.<br></div><div>To know more details click <span style="cursor: default;"><a href="|@link@|">here</a></span>.<br></div><div><br></div><div>If you are not able to click the link above, please copy and paste the link below to your browser.<br></div><div>|@link@|<br></div><div><br></div><div><div>Thanks,</div><div>Patients4Life Team</div></div>                                       ', '2013-11-23 05:45:18', '2013-11-26 05:47:49', '1', '1'),
(10, 'mail to all community members on delete group', 'Community has been removed', '\r\n\r\n                        <div><br></div>Hi&nbsp;|@username@|,<div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br><div>&nbsp; &nbsp; The community "|@group-name@|" has been removed by the owner.</div><div><br></div><div>Thanks,</div><div>Patients4Life Team</div></div></div>\r\n\r\n                                                                ', '2013-11-26 11:54:21', '2013-11-27 05:49:39', '1', '1');

--
-- Changing the `template_body` of email_template with id 6
-- 29-11-2013
--
UPDATE `email_templates` 
SET `template_body` = '\r\n\r\n\r\n\r\n<table class="table sortable no-margin" style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal; background-color: rgb(255, 255, 255); margin-left: 0.33em; margin-bottom: -0.67em;" width="100%" cellspacing="0"><tbody><tr><td class="padleft" colspan="2" width="100%"><div id="email_body_container"><br>Hi&nbsp;|@username@|,<div><div style="line-height: normal;"><br><div>The event "|@event-name@|" has been cancelled by the |@deleted-by@|.</div><div><br></div><div>Thanks,</div><div>Patients4Life Team</div></div></div></div></td></tr></tbody></table>\r\n\r\n'
WHERE `id` = 6;

-- -----------------------------------------------------------------------------
-- Adding 2 new email templates to 'email_templates' table
-- 04-12-2013
-- -----------------------------------------------------------------------------
INSERT INTO `email_templates` (`id`, `template_name`, `template_subject`, `template_body`, `created`, `modified`, `created_by`, `modified_by`) VALUES
(11, 'secondary admin notification mail', 'you have become the admin of group "|@group-name@|"', '&nbsp;Hi |@username@|,<div><br></div><div>You have been selected as one of the secondary admin of the group&nbsp;<a href="http://10.4.0.95:91/admin/EmailTemplates/edit/%7C@group-name@%7C">|@group-name@|</a>&nbsp;. Now you can have more actions on the above group.</div><div><br></div><div>Thanks,</div><div>Patients4life team.</div>                    ', '2013-12-03 09:13:14', '2013-12-03 13:08:24', '1', '1'),
(12, 'removing secondary admin notification mail', 'you are removed from the admin of group "|@group-name@|"', 'Hi&nbsp;|@username@|,<div><br></div><div>You have been removed from the admins list of group "|@group-name@|" by the admin.</div><div><br></div><div>Thanks,</div><div>patients4life team.</div>', '2013-12-03 11:50:32', '2013-12-03 12:48:09', '1', '1');

-- -----------------------------------------------------------------------------
-- Changed the mail sent on Invitation to join community
-- 05-12-2013
-- -----------------------------------------------------------------------------
UPDATE `email_templates` SET `template_body` = '<div><br></div>Hi |@username@|,<div><br></div><div>You have been invited to join the community |@group-name@|.<br></div><div>To know more details click <span style="cursor: default;"><a href="|@link@|">here</a></span>.<br></div><div><br></div><div>If you are not able to click the link above, please copy and paste the link below to your browser.<br></div><div>|@link@|<br></div><div><br></div><div><div>Thanks,</div><div>Patients4Life Team</div></div> ' WHERE `email_templates`.`id` =9;

-- Updated 2 templates by adding community page links.
-- 05-12-2013
-- -----------------------------------------------------------------------------
​
UPDATE `patients4life`.`email_templates` SET `template_body` = '
<span style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Hi |@username@|,</span><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">You have been selected as one of the secondary admin of the group "<a style=" text-decoration: none;" href="|@link@|">|@group-name@|</a>". Now you can have more actions on the above group.</div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Thanks,</div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Patients4life team.</div>'
WHERE `email_templates`.`id` = 11;

UPDATE `patients4life`.`email_templates` SET `template_body` = '
<table class="table sortable no-margin" cellspacing="0" width="100%" style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal; background-color: rgb(255, 255, 255); margin-left: 0.33em; margin-bottom: -0.67em;"><tbody><tr><td class="padleft" width="100%" colspan="2"><div id="email_body_container">Hi&nbsp;|@username@|,<div><br></div><div>You have been removed from the admins list of group "<a style=" text-decoration: none;" href="|@link@|">|@group-name@|</a>" by the admin.</div><div><br></div><div>Thanks,</div><div>patients4life team.</div></div></td></tr></tbody></table>'
WHERE `email_templates`.`id` = 12;​

-- -----------------------------------------------------------------------------
-- Changing 'group' to 'community'
-- 09-12-2013
-- -----------------------------------------------------------------------------
UPDATE `email_templates` SET `template_body` = ' <div><br></div>Hi |@username@|,<div><br></div><div>You have been invited to join the community |@community-name@|.<br></div><div>To know more details click <span style="cursor: default;"><a href="|@link@|" style="text-decoration: none; cursor: default;">here</a></span>.<br></div><div><br></div><div>If you are not able to click the link above, please copy and paste the link below to your browser.<br></div><div>|@link@|<br></div><div><br></div><div><div>Thanks,</div><div>Patients4Life Team</div></div> ' WHERE `email_templates`.`id` =9;

UPDATE `email_templates` SET `template_body` = ' <div><br></div>Hi&nbsp;|@username@|,<div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br><div>The community "|@community-name@|" has been removed by the owner.</div><div><br></div><div>Thanks,</div><div>Patients4Life Team</div></div></div> ' WHERE `email_templates`.`id` =10;

UPDATE `email_templates` SET `template_subject` = 'You have been added as the admin of community "|@community-name@|"', `template_body` = '
<span style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Hi |@username@|,</span><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">You have been selected as one of the secondary admin of the community "<a style=" text-decoration: none;" href="|@link@|">|@community-name@|</a>". Now you can have more actions on the above community.</div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;"><br></div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Thanks,</div><div style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal;">Patients4life team.</div>' WHERE `email_templates`.`id` = 11;

UPDATE `email_templates` SET `template_subject` = 'You have been removed from the admin list of community "|@community-name@|" ',
`template_body` = ' <table class="table sortable no-margin" cellspacing="0" width="100%" style="color: rgb(69, 74, 77); font-family: ''Helvetica Neue'', Arial, Helvetica, Geneva, sans-serif; line-height: normal; background-color: rgb(255, 255, 255); margin-left: 0.33em; margin-bottom: -0.67em;"><tbody><tr><td class="padleft" width="100%" colspan="2"><div id="email_body_container">Hi&nbsp;|@username@|,<div><br></div><div>You have been removed from the admins list of community "<a style=" text-decoration: none;" href="|@link@|">|@community-name@|</a>" by the admin.</div><div><br></div><div>Thanks,</div><div>patients4life team.</div></div></td></tr></tbody></table> ' WHERE `email_templates`.`id` =12;



--
-- Changing the welcome mail content
-- 31-01-2014
--
UPDATE `email_templates` 
SET `template_body` = '<div style="margin:-1px 0px 0px -35px;"><img alt="Welcome Banner" src="http://patients4life.qburst.com/theme/App/img/welcome_mail_bnr.png" /></div>\r\n\r\n <h2 style="font-size: 24px; margin: 30px 0px 25px 0px;  font-weight: normal;">Welcome to Patients4Life</h2>Hi |@username@|,<br><br>Congrats! You are successfully registered with Patients4Life using the following credentials:<br>Username:  |@username@|<br>Email:  |@email@|<br><br><div style="text-align:center">  <a style="color: #FFF; border: #f6861f; border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: #f6861f; display: inline-block; padding: 5px 20px; margin-bottom: 0px; font-size: 18px; font-weight: normal; line-height: 1.428571429; text-align: center; white-space: nowrap; vertical-align: middle; cursor: default; text-decoration: none; outline: none !important;" href="http://patients4life.qburst.com/">Visit Now &raquo;</a> </div> <br><p style="margin: 30px 0px 0px 0px;">Thanks,</p>\r\n<p style="margin: 1px 0px 0px 0px;">Patients4Life Team</p>                    '
WHERE `id` = 3;